* TODO

** DONE Explicação palavras-chave tela inicial

Pra facilitar, fizemos com que o sistema deva ser usado com termos semelhantes.

Exemplo, ao buscar aprendizagem, buscar aprendizado e aprendizagens.

Ou seja, não buscar aprendizagem e audiodescrição, pois virão coisas distintas.

Vindo termos semelhantes, todos irão direcionar para a raiz, que vai conter todas as respostas.

Por que não incluir as palavras chaves todas no final?

Pois é preciso buscar no texto e selecionar, as de aprendizagem e as de aprendizado. E ao final, posso querer incluir aprendiz, que sei que não consta no texto ou não quis procurar, mas que tem relação.

Acredito que uma explicação sobre isso na tela inicial é bem-vinda.

** DONE Palavra-Chave c minusculo inserir dois pontos
** DONE ingles -> pt

** DONE gerar patterns pras palavras-chave que o usuario insere no final
   CLOSED: [2018-05-28 Seg 16:41]


***** Colocar em Português o TinyMCE
* Criar um botão para gerar o arquivo AIML sem os recursos multimídia (só frases).
* Criar um botão para inserir mais caixas TinyMCE, em que o usuário possa inserir e editar mais frases manualmente.
***** Nome do Arquivo trocar por Nome do arquivo:
***** Palavras-Chave Relacionadas trocar por Palavras-chave relacionadas:
