# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_1', models.CharField(max_length=100)),
                ('keyword_2', models.CharField(max_length=100)),
                ('keyword_3', models.CharField(max_length=100)),
            ],
        ),
    ]
